services:
  nginx:
    image: nginx:alpine
    container_name: nginx-eventapp
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - eventapp

  backend:
    build:
      context: ./docker/laravel
    container_name: backend-app
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - eventapp

  frontend:
    image: node:20-alpine
    container_name: frontend-app
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    networks:
      - eventapp

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: eventapp
      POSTGRES_USER: eventapp
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - eventapp

  mailpit:
    image: axllent/mailpit
    container_name: mailpit-eventapp
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - eventapp
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "11434:11434"
    networks:
      - eventapp

volumes:
  postgres_data:

networks:
  eventapp:
    driver: bridge
